#!/bin/bash

#sudo add-apt-repository ppa:webupd8team/atom
#sudo apt-get update
#sudo apt-get install atom

apm install emmet &&
apm install autocomplete-plus &&
apm install autocomplete-html &&
apm install javascript-snippets &&
apm install project-manager &&
apm install git-diff &&
apm install save-session &&
apm install atom-beautify &&
apm install highlight-selected &&
apm install linter-jshint &&
apm install atom-ternjs &&

#themes
apm install monokai-seti &&
apm install seti-syntax &&
apm install seti-ui
