#!/bin/bash

#sudo add-apt-repository ppa:webupd8team/atom
#sudo apt-get update
#sudo apt-get install atom

sudo apm install emmet
sudo apm install autocomplete-plus
sudo apm install autocomplete-html
sudo apm install javascript-snippets
sudo apm install project-manager
sudo apm install git-diff
sudo apm install remember-session

sudo apm install monokai-seti
