#!/bin/bash
kasutaja=$USER
sudo adduser $kasutaja www-data
####################################################################################################################

#General 
sudo apt-get install -y xclip git chromium-browser vlc tilda mc p7zip-full unrar-free htop conky-all lm-sensors byobu nautilus-open-terminal #indicator-cpufreq thinkfan
####################################################################################################################

#Add repos
#Themes and docky
sudo add-apt-repository -y ppa:ricotz/docky &&
sudo add-apt-repository -y ppa:numix/ppa &&
#Atom and Sublime
sudo add-apt-repository -y ppa:webupd8team/atom &&
sudo add-apt-repository -y ppa:webupd8team/sublime-text-3 &&
#spotify
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys BBEBDCB318AD50EC6865090613B00F1FD2C19886 &&
echo deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list &&
#MongoDB
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927 &&
echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list &&

sudo apt-get update &&
sudo apt-get install -y atom sublime-text-installer spotify-client mongodb-org &&
sudo service mongod start
####################################################################################################################

#install python
sudo apt-get install -y python-dev libffi-devel build-essential python-pip &&
sudo pip install tornado numpy scipy pymongo pyyaml python-slugify pyexcel_ods3 python-magic requests PyJWT colorlog pyzmq jinja2 #cryptography
#or
# sudo apt-get install -y python-numpy python-scipy python-matplotlib ipython ipython-notebook python-pandas python-sympy python-nose python-tornado python-yaml
####################################################################################################################

#WebDev pack apache
sudo apt-get install -y apache2 &&
sudo a2enmod rewrite &&
sudo a2enmod userdir &&
sudo service apache2 reload &&
#Node 5
curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash - &&
sudo apt-get install -y nodejs &&
sudo npm install -g grunt grunt-cli bower yo generator-karma generator-angular
####################################################################################################################

#Look and feel
sudo apt-get install -y unity-tweak-tool plank numix-gtk-theme numix-icon-theme-circle gnome-tweak-tool &&
gsettings set org.gnome.desktop.interface gtk-theme 'Numix' &&
gsettings set org.gnome.desktop.interface icon-theme 'Numix-Circle' &&
#Autostart plank
echo '[Desktop Entry]
Type=Application
Exec=plank
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name[en_US]=plank
Name=plank
Comment[en_US]=
Comment=' > /home/server/.config/autostart/plank.desktop
####################################################################################################################

#Theme for gedit
gsettings set org.gnome.gedit.preferences.ui notebook-show-tabs-mode never && #Hides tabs
sudo wget https://gist.githubusercontent.com/LeoIannacone/71028cc3bce04567d77e/raw/7a9f77c9eabad2f9a08bce733ce8eb2586470fe8/monokai-exteded.xml -P /usr/share/gtksourceview-3.0/styles
####################################################################################################################

#Set up git and clone repos
git config --global user.email "mikk351@gmail.com" &&
git config --global user.name "mikk351" &&
ssh-keygen -t rsa -b 4096 -C "mikk351@gmail.com" &&
eval "$(ssh-agent -s)" && ssh-add ~/.ssh/id_rsa &&
xclip -sel clip < ~/.ssh/id_rsa.pub

mkdir ~/kood && cd ~/kood
git clone git@github.com:CCFFT/PyCalc-Backend.git &&
git clone git@github.com:CCFFT/PyCalc-Frontend.git &&
git clone git@bitbucket.org:mikkk/frontend.git &&
git clone git@bitbucket.org:mikkk/backend.git

cd ~/kood/PyCalc-Frontend && npm install && bower install &&
cd ~/kood/frontend && npm install && bower install
####################################################################################################################
