#!/bin/bash

sudo adduser $USER www-data
sudo ufw enable
sudo ufw allow ssh

# Look and feel
sudo add-apt-repository -y ppa:numix/ppa
sudo apt-get install -y numix-gtk-theme numix-icon-theme-circle gnome-tweak-tool &&
gsettings set org.gnome.desktop.interface gtk-theme 'Numix' && 
gsettings set org.gnome.desktop.interface icon-theme 'Numix-Circle'


#General 
####################################################################################################################
sudo apt-get install -y fail2ban shutter xclip git vlc tilda mc p7zip-full unrar-free htop byobu sshfs x2x openssh-server build-essential

#WGETS
####################################################################################################################
#Install ID card
wget https://installer.id.ee/media/install-scripts/install-open-eid.sh &&
chmod +x install-open-eid.sh &&
./install-open-eid.sh &&
rm install-open-eid.sh

#Google chrome
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb &&
sudo dpkg -i --force-depends google-chrome-stable_current_amd64.deb &&
rm google-chrome-stable_current_amd64.deb &&
sudo apt-get -f install

# Develop
####################################################################################################################
# Docker
sudo apt-get remove docker docker-engine docker.io
sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo apt-key fingerprint 0EBFCD88
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt-get update && sudo apt-get install -y docker-ce

# Node js
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash - &&
sudo apt-get update && sudo apt-get install -y nodejs


# VS code
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'

# ATOM
curl -sL https://packagecloud.io/AtomEditor/atom/gpgkey | sudo apt-key add -
sudo sh -c 'echo "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main" > /etc/apt/sources.list.d/atom.list'

# Subl3
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list

sudo apt-get update
sudo apt-get install -y sublime-text code atom

#Set up git and clone repos
####################################################################################################################
git config --global user.email "mikk351@gmail.com" &&
git config --global user.name "mikk351" &&
git config --global push.default simple &&
ssh-keygen -t rsa -b 4096 -C "mikk351@gmail.com" &&
eval "$(ssh-agent -s)" && ssh-add ~/.ssh/id_rsa &&
xclip -sel clip < ~/.ssh/id_rsa.pub

read -rsp $'SSH key copied to clipboard. Add it to github and press any key to continue. \n' -n1 key
