#!/bin/bash

sudo adduser $USER www-data
sudo ufw enable

#General 
####################################################################################################################
sudo apt-get install -y fail2ban shutter xclip git vlc tilda mc p7zip-full unrar-free htop byobu sshfs
sudo snap install spotify


#WGETS
####################################################################################################################
#Install ID card
wget https://installer.id.ee/media/install-scripts/install-open-eid.sh &&
chmod +x install-open-eid.sh &&
./install-open-eid.sh &&
rm install-open-eid.sh

#Google chrome
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb &&
sudo dpkg -i --force-depends google-chrome-stable_current_amd64.deb &&
rm google-chrome-stable_current_amd64.deb &&
sudo apt-get -f install


#Add repos
####################################################################################################################
#Atom and Sublime
sudo add-apt-repository -y ppa:webupd8team/atom &&
sudo add-apt-repository -y ppa:webupd8team/sublime-text-3 &


# Develop
####################################################################################################################
# Docker
sudo apt-get remove docker docker-engine docker.io
sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo apt-key fingerprint 0EBFCD88
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

sudo apt-get update && sudo apt-get install -y docker-ce


# Node js
curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash - &&


sudo apt-get install -y nodejs build-essential atom sublime-text-installe



#Set up git and clone repos
####################################################################################################################
git config --global user.email "mikk351@gmail.com" &&
git config --global user.name "mikk351" &&
git config --global push.default simple &&
ssh-keygen -t rsa -b 4096 -C "mikk351@gmail.com" &&
eval "$(ssh-agent -s)" && ssh-add ~/.ssh/id_rsa &&
xclip -sel clip < ~/.ssh/id_rsa.pub

read -rsp $'SSH key copied to clipboard. Add it to github and press any key to continue. \n' -n1 key
