#!/bin/bash

sudo adduser $USER www-data
####################################################################################################################

#General 
sudo apt-get install -y shutter xclip git chromium-browser vlc tilda mc p7zip-full unrar-free htop conky-all lm-sensors byobu nautilus-open-terminal #indicator-cpufreq thinkfan
####################################################################################################################

#Install ID card
wget https://installer.id.ee/media/install-scripts/install-open-eid.sh
chmod +x install-open-eid.sh
./install-open-eid.sh
####################################################################################################################

#Add repos
#Themes and docky
sudo add-apt-repository -y ppa:ricotz/docky &&
sudo add-apt-repository -y ppa:numix/ppa &&
#Atom and Sublime
sudo add-apt-repository -y ppa:webupd8team/atom &&
sudo add-apt-repository -y ppa:webupd8team/sublime-text-3 &&
#Spotify
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys BBEBDCB318AD50EC6865090613B00F1FD2C19886 &&
echo deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list &&
#MongoDB
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927 &&
echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list &&
#Docker
sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D &&
echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" | sudo tee /etc/apt/sources.list.d/docker.list &&

sudo apt-get update &&
sudo apt-get install -y atom sublime-text-installer spotify-client mongodb-org &&
sudo apt-get install -y linux-image-extra-$(uname -r) docker-engine && #Docker - The linux-image-extra package allows you use the aufs storage driver.
sudo service mongod start &&
sudo service docker start
sudo usermod -aG docker $USER 
####################################################################################################################

#Spotify icon fix
#sh -c "$(wget https://raw.githubusercontent.com/faviouz/fix-spotify-icon/master/install.sh -O -)"
#fix-spotify-icon

#install python and other dev packs
sudo apt-get install -y libblas-dev liblapack-dev libatlas-base-dev gfortran libxml2-dev libxslt1-dev libxslt1.1 python-dev build-essential python-pip &&
sudo pip install tornado numpy scipy pymongo pyyaml python-slugify pyexcel_ods3 python-magic requests PyJWT colorlog pyzmq jinja2 #cryptography
#or
# sudo apt-get install -y python-numpy python-scipy python-matplotlib ipython ipython-notebook python-pandas python-sympy python-nose python-tornado python-yaml
#All the things!
#sudo apt-get install build-essential autoconf libtool pkg-config python-opengl python-imaging python-pyrex python-pyside.qtopengl idle-python2.7 qt4-dev-tools qt4-designer libqtgui4 libqtcore4 libqt4-xml libqt4-test libqt4-script libqt4-network libqt4-dbus python-qt4 python-qt4-gl libgle3 python-dev
####################################################################################################################

#WebDev pack apache
sudo apt-get install -y apache2 &&
sudo a2enmod rewrite &&
sudo a2enmod userdir &&
sudo service apache2 reload &&
#Node 5
curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash - &&
sudo apt-get install -y nodejs &&
sudo npm install -g grunt grunt-cli bower yo generator-karma generator-angular
####################################################################################################################

#Look and feel
sudo apt-get install -y unity-tweak-tool plank numix-gtk-theme numix-icon-theme-circle gnome-tweak-tool &&
gsettings set org.gnome.desktop.interface gtk-theme 'Numix' &&
gsettings set org.gnome.desktop.interface icon-theme 'Numix-Circle' &&
#Autostart plank
echo '[Desktop Entry]
Type=Application
Exec=plank
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name[en_US]=plank
Name=plank
Comment[en_US]=
Comment=' > /home/$USER/.config/autostart/plank.desktop
echo '[Desktop Entry]
Type=Application
Exec=tilda
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name[en_US]=tilda
Name=tilda
Comment[en_US]=tilda
Comment=tilda' > /home/$USER/.config/autostart/tilda.desktop
####################################################################################################################

#Theme for gedit
gsettings set org.gnome.gedit.preferences.ui notebook-show-tabs-mode never && #Hides tabs
sudo wget https://gist.githubusercontent.com/LeoIannacone/71028cc3bce04567d77e/raw/7a9f77c9eabad2f9a08bce733ce8eb2586470fe8/monokai-exteded.xml -P /usr/share/gtksourceview-3.0/styles
####################################################################################################################

#Set up git and clone repos
git config --global user.email "mikk351@gmail.com" &&
git config --global user.name "mikk351" &&
ssh-keygen -t rsa -b 4096 -C "mikk351@gmail.com" &&
eval "$(ssh-agent -s)" && ssh-add ~/.ssh/id_rsa &&
xclip -sel clip < ~/.ssh/id_rsa.pub

read -rsp $'SSH key copied to clipboard. Add it to github and press any key to continue. \n' -n1 key

mkdir ~/kood && cd ~/kood
git clone git@github.com:CCFFT/PyCalc-Backend.git &&
git clone git@github.com:CCFFT/PyCalc-Frontend.git &&
git clone git@bitbucket.org:mikkk/frontend.git &&
git clone git@bitbucket.org:mikkk/backend.git

cd ~/kood/PyCalc-Frontend && npm install && bower install &&
cd ~/kood/frontend && npm install && bower install
####################################################################################################################

#Setting up backup
#Lista all settings
#gsettings list-recursively org.gnome.DejaDup
# NOT TESTED!!!
#gsettings set org.gnome.DejaDup exclude-list ['$TRASH', '$DOWNLOAD', '/home/$USER/deja-dup', '/home/$USER/sshMasin', '/home/$USER/kood/aAdmin/node_modules', '/home/$USER/kood/PyCalc-Frontend/node_modules', '/home/$USER/kood/Frontend/node_modules', '/home/$USER/kood/metarad/node_modules', '/home/$USER/kood/oscm/node_modules', '/home/$USER/.atom/.apm', '/home/$USER/.adobe', '/home/$USER/.atom', '/home/$USER/.java', '/home/$USER/.macromedia', '/home/$USER/.node-gyp', '/home/$USER/.npm', '/home/$USER/.rvm', '/home/$USER/.cache/dconf', '/home/$USER/.dbus', '/home/$USER/.gvfs']
