#!/bin/bash


#ADD Repos
#RPM Fusion
dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

#Fedy
sh -c 'curl https://www.folkswithhats.org/installer | bash' 


# Install packages
# General
dnf install -y mc htop git vim wget libnatpmp nautilus-open-terminal xclip plank fish gnome-tweak-tool chrome-gnome-shell

# ID Card
#dnf install -y estonianidcard esteidcerts firefox-esteid-plugin firefox-esteidpkcs11loader libdigidoc libdigidocpp qdigidoc qesteidutil

#Fonts
dnf install -y dejavu-sans-mono-fonts google-droid-sans-mono-fonts mozilla-fira-mono-fonts adobe-source-code-pro-fonts levien-inconsolata-fonts


# SSH key
ssh-keygen -t rsa -b 4096 -C "mikk351@gmail.com"
ssh-add ~/.ssh/id_rsa
eval "$(ssh-agent -s)"
